Fix bugs lp:1098360 and lp:1152764.
This commit fixes following:

a) lp:1098360:  Access denied for user debian-sys-maint 

Due to debian way of stopping/reloading/status checking, there was failure after
SST since the machine-specific debian maintenance password didn't work. This
fixes by using signals instead of mysqladmin as is done in CentOS. mysqld_safe
is also slightly modified so that wsrep-recover startup of mysqld uses different
pid file.

b) lp:1152764:  bootstrap option in init script 

Adds a new option 'bootstrap-pxc' to both Debian and CentOS init scripts which
can be used to bootstrap the cluster without any config modifications. It makes
use of --wsrep-new-cluster mysqld option added in lp:1087368. This option
overrides wsrep_cluster_address in my.cnf.

Credits to lefred for initially proposing the idea and the patch.

diff --git a/build/debian/percona-xtradb-cluster-server-5.5.mysql.init b/build/debian/percona-xtradb-cluster-server-5.5.mysql.init
--- a/build/debian/percona-xtradb-cluster-server-5.5.mysql.init
+++ b/build/debian/percona-xtradb-cluster-server-5.5.mysql.init
@@ -24,7 +24,6 @@ test -x "${PERCONA_PREFIX}"/sbin/mysqld || exit 0
 
 SELF=$(cd $(dirname $0); pwd -P)/$(basename $0)
 CONF=/etc/mysql/my.cnf
-MYADMIN="${PERCONA_PREFIX}/bin/mysqladmin --defaults-file=/etc/mysql/debian.cnf"
 
 # priority can be overriden and "-s" adds output to stderr
 ERR_LOGGER="logger -p daemon.err -t /etc/init.d/mysql -i"
@@ -67,6 +66,14 @@ sanity_checks() {
   fi
 }
 
+# Get the pid file
+mysql_data_dir=$(mysqld_get_param datadir)
+[ ! $mysql_data_dir ] && mysql_data_dir="/var/lib/mysql"
+
+pid_file=$(mysqld_get_param pid-file)
+[ ! $pid_file ] && pid_file="$mysql_data_dir/$(hostname).pid"
+
+
 ## Checks if there is a server running and if so if it is accessible.
 #
 # check_alive insists on a pingable server
@@ -74,18 +81,34 @@ sanity_checks() {
 #
 # Usage: boolean mysqld_status [check_alive|check_dead] [warn|nowarn]
 mysqld_status () {
-    ping_output=`$MYADMIN ping 2>&1`; ping_alive=$(( ! $? ))
+    mysqld_pid=$(cat $pid_file 2>/dev/null)
 
+    if [ ! $mysqld_pid ];then 
+        echo "MySQL PID not found, pid_file detected/guessed: $pid_file" | $ERR_LOGGER
+        if [ "$1" = "check_dead" ]; then
+            return 0
+        fi
+        return 1
+    fi
+
+    ping_alive=1
     ps_alive=0
-    pidfile=`mysqld_get_param pid-file`
-    if [ -f "$pidfile" ] && ps `cat $pidfile` >/dev/null 2>&1; then ps_alive=1; fi
+    
+    output=$(mysql -u root -pabcd -e 'select 1;' 2>&1 | grep -q 'ERROR 2002')
+    [ $output ] && ping_alive=0
+    
+    /bin/kill -0 $mysqld_pid &>/dev/null && ps_alive=1
     
     if [ "$1" = "check_alive"  -a  $ping_alive = 1 ] ||
        [ "$1" = "check_dead"   -a  $ping_alive = 0  -a  $ps_alive = 0 ]; then
 	return 0 # EXIT_SUCCESS
     else
   	if [ "$2" = "warn" ]; then
-  	    echo -e "$ps_alive processes alive and '$MYADMIN ping' resulted in\n$ping_output\n" | $ERR_LOGGER -p daemon.debug
+  	    warn_msg=
+  	    [ $ping_alive = 0 ] && warn_msg+="mysql ping failed"
+  	    [ $ps_alive = 0 ] && \
+  	        warn_msg+=" and/or mysqld with pid $mysqld_pid is not alive"
+  	    echo -e "$warn_msg" | $ERR_LOGGER -p daemon.debug
 	fi
   	return 1 # EXIT_FAILURE
     fi
@@ -111,15 +134,18 @@ case "${1:-''}" in
 	        if mysqld_status check_alive nowarn ; then break; fi
 		log_progress_msg "."
 	    done
-	    if mysqld_status check_alive warn; then
+            if mysqld_status check_alive warn; then
                 log_end_msg 0
-	        # Now start mysqlcheck or whatever the admin wants.
-	        output=$(/etc/mysql/debian-start)
-		[ -n "$output" ] && log_action_msg "$output"
-	    else
-	        log_end_msg 1
-		log_failure_msg "Please take a look at the syslog"
-	    fi
+                # Now start mysqlcheck or whatever the admin wants.
+                # only if the file /etc/mysql/NO-DEBIAN-START is absent.
+                if ! test -e /etc/mysql/NO-DEBIAN-START;then
+                    output=$(/etc/mysql/debian-start)
+                    [ -n "$output" ] && log_action_msg "$output"
+                fi
+            else
+                log_end_msg 1
+                log_failure_msg "Please take a look at the syslog"
+            fi
 	fi
 	;;
 
@@ -131,25 +157,28 @@ case "${1:-''}" in
 	log_daemon_msg "Stopping MySQL (Percona XtraDB Cluster)" "mysqld"
 	if ! mysqld_status check_dead nowarn; then
 	  set +e
-	  shutdown_out=`$MYADMIN shutdown 2>&1`; r=$?
+	  shutdown_out=`kill $mysqld_pid 2>&1`; r=$?
 	  set -e
 	  if [ "$r" -ne 0 ]; then
 	    log_end_msg 1
-	    [ "$VERBOSE" != "no" ] && log_failure_msg "Error: $shutdown_out"
-	    log_daemon_msg "Killing MySQL (Percona XtraDB Cluster) by signal" "mysqld"
-	    killall -15 mysqld
+	    log_daemon_msg "MySQLd already dead" "mysqld"
+	  else
             server_down=
 	    for i in 1 2 3 4 5 6 7 8 9 10; do
               sleep 1
               if mysqld_status check_dead nowarn; then server_down=1; break; fi
             done
-          if test -z "$server_down"; then killall -9 mysqld; fi
+            #Better to not kill in cases of large buffer pools
+            #if test -z "$server_down"; then 
+                #kill -9 $mysqld_pid 
+            #fi
 	  fi
         fi
 
         if ! mysqld_status check_dead warn; then
 	  log_end_msg 1
-	  log_failure_msg "Please stop MySQL (Percona XtraDB Cluster) manually and read /usr/share/doc/percona-server-server-5.5/README.Debian.gz!"
+	  log_failure_msg "Please stop MySQL (Percona XtraDB Cluster) manually and \
+	      read /usr/share/doc/percona-server-server-5.5/README.Debian.gz!"
 	  exit -1
 	else
 	  log_end_msg 0
@@ -163,21 +192,63 @@ case "${1:-''}" in
 
   'reload'|'force-reload')
   	log_daemon_msg "Reloading MySQL (Percona XtraDB Cluster)" "mysqld"
-	$MYADMIN reload
-	log_end_msg 0
+        mysqld_pid=$(cat $pid_file 2>/dev/null)
+
+        if [ ! $mysqld_pid ];then 
+            log_failure_msg "MySQL PID not found, pid_file detected/guessed: $pid_file"
+            log_end_msg 1
+            exit 4
+        fi
+
+  	if kill -HUP $mysqld_pid 2>/dev/null;then 
+  	    log_daemon_msg "Percona XtraDB Cluster reload complete" "mysqld"
+            log_end_msg 0
+  	else
+            log_failure_msg "Percona XtraDB Cluster with PID $mysqld_pid \
+                            is not running or unknown error"
+            log_end_msg 1
+        fi
 	;;
 
   'status')
 	if mysqld_status check_alive nowarn; then
-	  log_action_msg "$($MYADMIN version)"
+	  log_action_msg "Percona XtraDB Cluster up and running"
 	else
-	  log_action_msg "MySQL (Percona XtraDB Cluster) is stopped."
+	  log_action_msg "MySQL (Percona XtraDB Cluster) is stopped. Check log"
 	  exit 3
 	fi
   	;;
-
+  'bootstrap-pxc')
+	sanity_checks;
+	# Start daemon
+	log_daemon_msg "Bootstrapping MySQL (Percona XtraDB Cluster) database server" "mysqld"
+	if mysqld_status check_alive nowarn; then
+	   log_progress_msg "already running"
+	   log_end_msg 0
+	else
+  	    "${PERCONA_PREFIX}"/bin/mysqld_safe --wsrep-new-cluster > /dev/null 2>&1 &
+	    # 6s was reported in #352070 to be too few when using ndbcluster
+	    for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14; do
+                sleep 1
+	        if mysqld_status check_alive nowarn ; then break; fi
+		log_progress_msg "."
+	    done
+            if mysqld_status check_alive warn; then
+                log_end_msg 0
+                # Now start mysqlcheck or whatever the admin wants.
+                # only if the file /etc/mysql/NO-DEBIAN-START is absent.
+                if ! test -e /etc/mysql/NO-DEBIAN-START;then
+                    output=$(/etc/mysql/debian-start)
+                    [ -n "$output" ] && log_action_msg "$output"
+                fi
+            else
+                log_end_msg 1
+                log_failure_msg "Please take a look at the syslog"
+            fi
+	fi
+	;;
   *)
-	echo "Usage: $SELF start|stop|restart|reload|force-reload|status"
+	echo "Usage: $SELF start|stop|restart|reload|force-reload|status|bootstrap-pxc"
 	exit 1
 	;;
 esac
