More systemd fixes

diff --git a/build-ps/rpm/mysql-systemd-start b/build-ps/rpm/mysql-systemd-start
--- a/build-ps/rpm/mysql-systemd-start
+++ b/build-ps/rpm/mysql-systemd-start
@@ -11,18 +11,18 @@
 parse_cnf()
 {
     local var=$1
+    local def=$2
     shift
     local groups=$*
     reval=$(my_print_defaults $groups | awk -F= '{if ($1 ~ /_/) { gsub(/_/,"-",$1); print $1"="$2 } else { print $0 }}' | grep -- "--$var=" | cut -d= -f2-)
     if [[ -z ${reval:-} ]];then 
-        reval=""
+        reval="$def"
     fi
     echo $reval
 }
 
 install_db () {    
     # Note: something different than datadir=/var/lib/mysql requires SELinux policy changes (in enforcing mode)
-    datadir=$(parse_cnf datadir server mysqld)
     log=$(parse_cnf log-error server mysqld)
 
 
@@ -67,6 +67,10 @@ log_failure_msg() {
     echo " ERROR! $@"
 }
 
+log_info_msg() {
+    echo " INFO: $@"
+}
+
 wait_for_pid () {
   local verb=$1          
   local pid_file_path="$2" 
@@ -85,6 +89,7 @@ wait_for_pid () {
 
   while [[ $i -lt $service_startup_timeout ]]; do
 
+    set +e
     case "$verb" in
       'created')
             if [[ -s "$pid_file_path" ]]; then 
@@ -106,12 +111,15 @@ wait_for_pid () {
         exit 1
         ;;
     esac
+    set -e
 
 
-    if ([[ -e $sst_progress_file ]] || grep -q -- '--wsrep-new-cluster' $env_file ) \
-        && [[ $startup_sleep -ne 10 ]];then
-        echo "State transfer in progress, setting sleep higher"
-        startup_sleep=10
+    if [[ $verb = 'created' ]];then 
+        if ([[ -e $sst_progress_file ]] || grep -q -- '--wsrep-new-cluster' <<< $env_args ) \
+            && [[ $startup_sleep -ne 10 ]];then
+            echo "State transfer in progress, setting sleep higher"
+            startup_sleep=10
+        fi
     fi
 
     i=$(( i+1 ))
@@ -123,7 +131,7 @@ wait_for_pid () {
     log_success_msg
     return 0
   elif [[ -e $sst_progress_file ]]; then 
-    log_failure_msg
+    log_info_msg
     return 2
   else
     log_failure_msg
@@ -140,14 +148,15 @@ bindir="$basedir/bin"
 sbindir="$basedir/sbin"
 libexecdir="$basedir/libexec"
 
+env_args="${EXTRA_ARGS:-}"
+
 
 PATH="/sbin:/usr/sbin:/bin:/usr/bin:$basedir/bin"
 export PATH
 
-pid_path=$(parse_cnf pid-file server mysqld)
-datadir=$(parse_cnf datadir server mysqld)
-service_startup_timeout=$(parse_cnf service-startup-timeout server mysqld)
-env_file="/etc/sysconfig/mysql"
+pid_path=$(parse_cnf pid-file "" server mysqld)
+datadir=$(parse_cnf datadir "" server mysqld)
+service_startup_timeout=$(parse_cnf service-startup-timeout $service_startup_timeout server mysqld)
 
 if [[ -z ${datadir:-} ]];then
     datadir="/var/lib/mysql"
@@ -176,7 +185,7 @@ case $1 in
       if [ $return_value == 1 ];then 
           log_failure_msg "MySQL (Percona XtraDB Cluster) server startup failed!"
       elif [ $return_value == 2 ];then
-          log_failure_msg "MySQL (Percona XtraDB Cluster) server startup failed! State transfer still in progress"
+          log_info_msg "MySQL (Percona XtraDB Cluster) server startup failed! State transfer still in progress"
       fi
       exit $return_value
     ;;
