First version that works SST and IST

diff --git a/scripts/wsrep_sst_clone b/scripts/wsrep_sst_clone
--- a/scripts/wsrep_sst_clone
+++ b/scripts/wsrep_sst_clone
@@ -29,6 +29,9 @@ progress_monitor=""
 PARENT_PID=""
 CLEANUP_CLONE_PLUGIN=""
 CLEANUP_CLONE_SSL=""
+CLONE_USER=""
+TSST_PORT=4444
+
 
 # wsrep_gen_secret() generates enough randomness, yet some MySQL password
 # policy may insist on having upper and lower case letters, numbers and
@@ -71,11 +74,12 @@ cleanup_donor()
         then
             $MYSQL_ACLIENT -e "SET GLOBAL clone_ssl_cert='';
                                SET GLOBAL clone_ssl_key='';
-                               SET GLOBAL clone_ssl_ca='';"
+                               SET GLOBAL clone_ssl_ca='';" || :
         fi
     fi
-
-    $MYSQL_ACLIENT -e "DROP USER IF EXISTS '$CLONE_USER';  SET wsrep_on = OFF; $CLEANUP_CLONE_PLUGIN"
+    if [ ! "$CLONE_USER" == "" ]; then  
+        $MYSQL_ACLIENT -e "DROP USER IF EXISTS '$CLONE_USER';  SET wsrep_on = OFF; $CLEANUP_CLONE_PLUGIN" || : 
+    fi
 
     [ "$CLONE_PREPARE_SQL" ] && rm -rf "$CLONE_PREPARE_SQL" ||:
     [ "$CLONE_EXECUTE_SQL" ] && rm -rf "$CLONE_EXECUTE_SQL" ||:
@@ -92,6 +96,8 @@ cleanup_joiner()
 
     rm -rf $CLONE_SOCK_DIR || :
     rm -rf $CLONE_PID_FILE || :
+    rm -fr $tmp_datadir || :
+    rm -f $WSREP_SST_OPT_DATA/IST_FILE.txt || :
 #   if [ $CLEANUP_FILES ]
 #    then
 #        rm -rf $CLONE_ERR
@@ -526,33 +532,34 @@ EOF
             esac
             exit $RC
         fi
-
+        cleanup_donor
     else # BYPASS
         wsrep_log_info "Bypassing state dump."
 
         # Instruct recipient to shutdown
-        export MYSQL_PWD="$RECIPIENT_PSWD"
-        wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAA -> BYPASS SENDING SHUTDOWN TO JOINER $MYSQL_RCLIENT $MYSQL_RCLIENT"
+        #export MYSQL_PWD="$RECIPIENT_PSWD"
+        wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAA -> BYPASS SENDING IST_FILE TO JOINER NetCat: nc $WSREP_SST_OPT_HOST $TSST_PORT"
+        echo $WSREP_SST_OPT_GTID | nc $WSREP_SST_OPT_HOST $TSST_PORT || : 
+        sleep 10
         wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAA -> Exiting with gtid: $WSREP_SST_OPT_GTID"
-        echo "done $WSREP_SST_OPT_GTID"
 
        # eval $MYSQL_RCLIENT --connect-timeout=60 $CLIENT_SSL_OPTIONS -e "SHUTDOWN"
     fi
     export MYSQL_PWD=$ADMIN_PSWD
     wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAA -> SENDING DONE $ADMIN_PSWD | $MYSQL_PWD | $WSREP_SST_OPT_GTID"
     #DONOR must be clean BEFORE exit given user is removed on DONE
-    cleanup_donor
+    
     echo "done $WSREP_SST_OPT_GTID"
 
 elif [ "$WSREP_SST_OPT_ROLE" = "joiner" ]
 then
-    wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAA -> wsrep_sst_clone JOINER "
-    wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAA -> JOINER EXITING WITH ready clone_sst:pippo]10.0.0.21:6666"
-    echo "ready clone_sst:pippo]10.0.0.21:6666"
-    sleep 10    
-    echo "25849473-611b-11ee-a815-1e6eed6a032d:867"
+#    wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAA -> wsrep_sst_clone JOINER "
+#    wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAA -> JOINER EXITING WITH ready clone_sst:pippo]10.0.0.21:6666"
+#    echo "ready clone_sst:pippo]10.0.0.21:6666"
+#    sleep 10    
+#    echo "25849473-611b-11ee-a815-1e6eed6a032d:867"
     
-    exit 0
+#    exit 0
     
     CLEANUP_FILES=""
     wsrep_check_programs grep
@@ -692,9 +699,18 @@ then
 
     CLONE_ERR="$WSREP_SST_OPT_DATA/$MODULE.err"
     CLONE_SQL="$WSREP_SST_OPT_DATA/$MODULE.sql"
+    IST_FILE="$WSREP_SST_OPT_DATA/IST_FILE.txt
+    GRASTATE_FILE="$tmp_datadir/grastate.dat
 
-    CLONE_SOCK="${tmp_datadir}/recover_clone.sock"
-    CLONE_X_SOCK="$tmp_datadir/cmysqlx.sock"
+#    CLONE_SOCK="${tmp_datadir}/recover_clone.sock"
+#    CLONE_X_SOCK="$tmp_datadir/cmysqlx.sock"
+    CLONE_SOCK="$WSREP_SST_OPT_DATA/recover_clone.sock"
+    CLONE_X_SOCK="$WSREP_SST_OPT_DATA/cmysqlx.sock"
+
+    IST_SOCK="$WSREP_SST_OPT_DATA/recover_ist.sock"
+    IST_X_SOCK="$WSREP_SST_OPT_DATA/cmysqlx_ist.sock"
+
+    
     if [ ${#CLONE_X_SOCK} -ge 104 ]
     then
         wsrep_log_error "Unix socket path name length for CLONE SST receiver"\
@@ -724,7 +740,7 @@ then
      $DEFAULTS_FILE_OPTION \
      $DEFAULTS_GROUP_OPTION \
      $INVARIANT_OPTIONS \
-     --datadir='$tmp_datadir' \
+     --datadir='$WSREP_SST_OPT_DATA' \
      --wsrep_on=0 \
      --secure_file_priv='' \
      --socket="$CLONE_SOCK" \
@@ -739,16 +755,36 @@ then
      --skip-mysqlx \
     "
 
+    DEFAULT_OPTIONS_IST=" \
+     $DEFAULTS_FILE_OPTION \
+     $DEFAULTS_GROUP_OPTION \
+     $INVARIANT_OPTIONS \
+     --datadir='$WSREP_SST_OPT_DATA' \
+     --wsrep_on=0 \
+     --secure_file_priv='' \
+     --socket="$CLONE_SOCK" \
+     --mysqlx_socket="$CLONE_X_SOCK" \
+     --log_error='$CLONE_ERR' \
+     --pid_file='$CLONE_PID_FILE' \
+     --plugin-dir='$CLONE_LIBS' \
+     --port='$CLONE_PORT' \
+    "
+
+
+
+
     if [ ! -d "$WSREP_SST_OPT_DATA/mysql" -o \
          ! -r "$WSREP_SST_OPT_DATA/mysql.ibd" ]
     then
         # No data dir, need to initialize one first, to make connections to
         # this node possible.
         # We need to use a temporary empty data directory, because the
-        # actual datadir may already contain some wsrep-related files
-        # tmp_datadir=$(wsrep_mktemp_in_dir "$WSREP_SST_OPT_DATA" -d)
+        # actual datadir may already contain some wsrep-related files    
         wsrep_log_info "Initializing data directory at $tmp_datadir"
 
+        wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAA -> INITIALIZE DB"  
+        #reset CLONE log
+        echo "" > $CLONE_ERR
         eval $CLONE_ENV $CLONE_BINARY $DEFAULT_OPTIONS \
              $SKIP_NETWORKING_OPTIONS \
              --initialize --wsrep_provider=none --datadir="$tmp_datadir" >> $CLONE_ERR 2>&1 || \
@@ -759,12 +795,15 @@ then
           done
           wsrep_log_error "Full log at $CLONE_ERR"
           exit 1 )
-
-#        # move initialized data directory structure to real datadir and cleanup
-#        mv --force "$tmp_datadir"/* "$WSREP_SST_OPT_DATA/"
-#        rm -rf "$tmp_datadir"
-    fi
-
+          
+                # move initialized data directory structure to real datadir and cleanup
+        mv --force "$tmp_datadir"/* "$WSREP_SST_OPT_DATA/"
+        sleep 2
+        wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAA -> REMOVE $tmp_datadir"  
+        rm -rf "$tmp_datadir"
+  
+        wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAA -> INITIALIZE DB DONE"  
+    fi 
     CLONE_USER="clone_sst_$(date +%y%m%d_%H%M%S)"
     CLONE_PSWD=`wsrep_gen_secret`"$PSWD_POLICY"
     CLONE_USER="clone_sst"
@@ -835,6 +874,7 @@ EOF
         if [ $to_wait -eq 0 ]
         then
             wsrep_log_error "Timeout waiting for clone recipient daemon"
+            kill -9 $CLONE_REAL_PID || :
             exit $ETIMEDOUT
         fi
         to_wait=$(( $to_wait - 1 ))
@@ -844,13 +884,22 @@ EOF
     MYSQL_ACLIENT="$MYSQL_CLIENT -u$CLONE_USER -S$CLONE_SOCK \
                    --batch --skip_column_names --silent"
     setup_clone_plugin "recipient"
+
     wsrep_log_info "AAAAAAAAAAAAAAAAAAA Joiner setup."
 
+
+    #OPEN NETCAT to receive messages from DONOR (like IST)
+    wsrep_log_info "AAAAAAAAAAAAAAAAAAA -> Opening NETCAT: nc -l $WSREP_SST_OPT_HOST $TSST_PORT"
+    nc -l $WSREP_SST_OPT_HOST $TSST_PORT > $WSREP_SST_OPT_DATA/IST_FILE.txt & 
+    NC_PID=$!
+    wsrep_log_info "AAAAAAAAAAAAAAAAAAA -> NETCAT PID $NC_PID"
+    
+   
     # Report clone credentials/address to the caller
     wsrep_log_info "AAAAAAAAAAAAAAAAAAA ready passing string |$CLONE_USER:$CLONE_PSWD@$WSREP_SST_OPT_HOST:$CLONE_PORT|"
     echo "ready $CLONE_USER:$CLONE_PSWD]$WSREP_SST_OPT_HOST:$CLONE_PORT"
 
-    wsrep_log_info "AAAAAAAAAAAAAAAAAAA -> CHECKING PROGRESS? [$PROGRESS]" 
+#    wsrep_log_info "AAAAAAAAAAAAAAAAAAA -> CHECKING PROGRESS? [$PROGRESS]" 
     
     # if [ -z "$PROGRESS" ]
     # then
@@ -868,11 +917,38 @@ EOF
     do
         wsrep_log_debug "Checking parent: $WSREP_SST_OPT_PARENT"
         check_parent $WSREP_SST_OPT_PARENT
+        
+        #ADD here the check for IST_FILE
+        wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAAAAAAA -> Checking IST File "
+        if [ -s  $WSREP_SST_OPT_DATA/IST_FILE.txt ];then
+         
+         kill -15 $CLONE_REAL_PID
+         wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAAAAAAA -> IST FILE is present closing SST process"
+                   
+         #recover Position to send
+         wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAAAAAAA -> RECOVER POSITION TO SEND OUT DOR IST"
+         RP_PURGED=`cat $WSREP_SST_OPT_DATA/IST_FILE.txt`   
+#         eval $CLONE_ENV $CLONE_BINARY $DEFAULT_OPTIONS_IST $SKIP_NETWORKING_OPTIONS \
+#         --wsrep_recover >> $CLONE_ERR 2>&1
+#           
+#         RP="$(grep -a '\[WSREP\] Recovered position:' $CLONE_ERR || :)"
+#         RP_PURGED=`echo $RP | sed 's/.*WSREP\]\ Recovered\ position://' | sed 's/^[ \t]*//'`
+         wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAAAAAAA -> POSITION: $RP_PURGED"         
+         echo $RP_PURGED
+         rm -f $CLONE_ERR || :
+         rm -f  $WSREP_SST_OPT_DATA/IST_FILE.txt || :
+         kill -15 $NC_PID || :
+         exit 0
+        fi
+        
         sleep 0.5
     done
+       
     CLONE_REAL_PID=0
     wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAAAAAAA -> clone recepient daemon finished"
-    
+    wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAAAAAAA -> Closing NETCAT"
+    kill -9 $NC_PID || :
+ 
     if [ -n "$progress_monitor" ]
     then
         # Make sure monitoring thread dies
@@ -882,10 +958,8 @@ EOF
 
     wsrep_log_info "Performing data recovery"
 
-#   --wsrep_provider=none \
-#    --wsrep_recover
     wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAAAAAAA -> RECOVERY COMMAND LINE: $CLONE_ENV $CLONE_BINARY $DEFAULT_OPTIONS $SKIP_NETWORKING_OPTIONS"
-#TRY    
+
     wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAAAAAAA -> FIRST RESTART for fixing dictionary"
     echo > $CLONE_PID_FILE
     eval $CLONE_ENV $CLONE_BINARY $DEFAULT_OPTIONS $SKIP_NETWORKING_OPTIONS --wsrep_provider=none &
@@ -931,6 +1005,27 @@ EOF
     RP="$(grep -a '\[WSREP\] Recovered position:' $CLONE_ERR || :)"
     RP_PURGED=`echo $RP | sed 's/.*WSREP\]\ Recovered\ position://' | sed 's/^[ \t]*//'`
     wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAAAAAAA -> POSITION: $RP_PURGED"
+
+    if [ ! "$RP_PURGED" == ""]; then
+        
+        ORIG_IFS=$IFS    
+        IFS=';'
+        read -ra gtid_arr <<< "$RP_PURGED"
+        uuid="${gtid_arr[1]}"
+        position="${gtid_arr[0]}"
+        IFS=$ORIG_IFS
+        wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAAAAAAA -> Creating grastate.dat file in $GRASTATE_FILE UUID: $uuid POSITION: $position"
+cat << EOF > "$GRASTATE_FILE"
+# GALERA saved state
+version: 2.1
+uuid:    $uuid
+seqno:   $position
+safe_to_bootstrap: 0
+EOF
+        
+    fi
+    
+ 
     
     
     # Remove created clone user
@@ -946,10 +1041,10 @@ EOF
        --wsrep_provider=none  --init-file="$CLONE_SQL" >> $CLONE_ERR 2>&1
          
      
-    # move initialized data directory structure to real datadir and cleanup
-      wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAAAAAAA -> MOVE DATA FILES from $tmp_datadir TO $WSREP_SST_OPT_DATA "
-      eval mv --force '${tmp_datadir}/* ${WSREP_SST_OPT_DATA}/' 
-      rm -rf $tmp_datadir 
+#@@@    # move initialized data directory structure to real datadir and cleanup
+#      wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAAAAAAA -> MOVE DATA FILES from $tmp_datadir TO $WSREP_SST_OPT_DATA "
+#      eval mv --force '${tmp_datadir}/* ${WSREP_SST_OPT_DATA}/' 
+#      rm -rf $tmp_datadir 
 
       if [ "$?" == "0" ]; then
         wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAAAAAAA -> MOVE DATA FILES DONE" 
@@ -983,7 +1078,7 @@ EOF
         # CLEANUP_FILES=1
         
     # fi
-    forcing restart of parent
+    #forcing restart of parent
     # wsrep_log_info "AAAAAAAAAAAAAAAAAAAAAAAAAAAA -> RESTARTING PARENT $PARENT_PID"
     # kill -9 $PARENT_PID
 else
