Working version also on MTR. I still need to find a way to be sure netcat is not running

diff --git a/scripts/wsrep_sst_clone b/scripts/wsrep_sst_clone
--- a/scripts/wsrep_sst_clone
+++ b/scripts/wsrep_sst_clone
@@ -46,6 +46,7 @@ OS=$(uname)
 
 . $(dirname "$0")/wsrep_sst_common_clone
 
+
 wsrep_log_info "Running: $CMDLINE"
 
 MYPID=$$
@@ -344,7 +345,7 @@ then
     if test -z "$WSREP_SST_OPT_USER";   then wsrep_log_error "USER cannot be nil";   exit $EINVAL; fi
     if test -z "$WSREP_SST_OPT_REMOTE_USER"; then wsrep_log_error "REMOTE_USER cannot be nil"; exit $EINVAL; fi
     if test -z "$WSREP_SST_OPT_PORT";   then wsrep_log_error "PORT cannot be nil";   exit $EINVAL; fi
-    if test -z "$WSREP_SST_OPT_LPORT";  then wsrep_log_error "LPORT cannot be nil";  exit $EINVAL; fi
+#    if test -z "$WSREP_SST_OPT_LPORT";  then wsrep_log_error "LPORT cannot be nil";  exit $EINVAL; fi
     if test -z "$WSREP_SST_OPT_SOCKET"; then wsrep_log_error "SOCKET cannot be nil"; exit $EINVAL; fi
 
     CLIENT_VERSION=$($MYSQL_CLIENT --version | grep -vi MariaDB | cut -d ' ' -f 4)
@@ -359,7 +360,13 @@ then
                    -P$WSREP_SST_OPT_PORT --batch --skip_column_names --silent"
     MYSQL_ACLIENT="$MYSQL_CLIENT -u$ADMIN_USER -S$WSREP_SST_OPT_SOCKET \
                    --batch --skip_column_names --silent"
-    
+ 
+    if [ -z "$WSREP_SST_OPT_LPORT" ]; then
+       export MYSQL_PWD=$ADMIN_PSWD
+       readonly WSREP_SST_OPT_LPORT=`MYSQL_ACLIENT -e "select @@port" 2> /dev/null` || : 
+    fi
+ 
+    wsrep_log_debug "-> WSREP_SST_OPT_LPORT: $WSREP_SST_OPT_LPORT "
     wsrep_log_debug "-> MYSQL_ACLIENT: $MYSQL_ACLIENT "
     wsrep_log_debug "-> MYSQL_ACLIENT ADMIN_PSWD: $ADMIN_PSWD"
     wsrep_log_debug "-> MYSQL_RCLIENT: $MYSQL_RCLIENT "
@@ -426,7 +433,7 @@ EOF
         while [ 1 == 1 ]; do
         	NCPING=`nc -w 0.5 -i 0.5 $SST_HOST_STRIPPED $WSREP_SST_OPT_PORT 2> /dev/null` || : 
             if [ "$NCPING" == "" ]; then
-                wsrep_log_info "[time to timeout: $TIMOUT_WAIT_JOINER_CLONE_INSTANCE]"
+                wsrep_log_info "[second(s) to timeout: $TIMOUT_WAIT_JOINER_CLONE_INSTANCE]"
             else 
                 wsrep_log_info "Joiner instance available at $SST_HOST_STRIPPED:$WSREP_SST_OPT_PORT"
                 break
@@ -690,7 +697,7 @@ then
      --wsrep_on=0 \
      --secure_file_priv='' \
      --socket="$CLONE_SOCK" \
-     --mysqlx_socket="$CLONE_X_SOCK" \
+     --skip-mysqlx \
      --log_error='$CLONE_ERR' \
      --pid_file='$CLONE_PID_FILE' \
      --plugin-dir='$CLONE_LIBS' \
@@ -716,10 +723,14 @@ then
     # 4) IF SST Process continue 
 
     #OPEN NETCAT to receive messages from DONOR (like IST)
-    wsrep_log_debug "-> Opening NETCAT: nc -l $WSREP_SST_OPT_HOST $TSST_PORT"
+    wsrep_log_info "-> Opening NETCAT: nc -l $WSREP_SST_OPT_HOST $TSST_PORT"
     nc -l -k $WSREP_SST_OPT_HOST $TSST_PORT > $WSREP_SST_OPT_DATA/XST_FILE.txt & 
     NC_PID=$!
-    wsrep_log_debug "-> NETCAT PID $NC_PID"
+    wsrep_log_info "-> NETCAT PID $NC_PID"
+    if [ "$NC_PID" == "" ];then
+        wsrep_log_error "-> Cannot open Netcat at given port $WSREP_SST_OPT_HOST $TSST_PORT check if the port is already taken"
+        exit 1
+    fi
     
     # Report clone credentials/address to the caller
     wsrep_log_debug "-> ready passing string |$CLONE_USER:$CLONE_PSWD]$WSREP_SST_OPT_HOST:$CLONE_PORT|"
@@ -746,7 +757,7 @@ then
          RP_PURGED=`cat $WSREP_SST_OPT_DATA/XST_FILE.txt`   
          wsrep_log_debug "-> POSITION: $RP_PURGED"         
          echo $RP_PURGED
-         rm -f $CLONE_ERR || :
+#         rm -f $CLONE_ERR || :
          rm -f  $WSREP_SST_OPT_DATA/XST_FILE.txt || :
          kill -15 $NC_PID || : > /dev/null 2>&1
          exit 0
@@ -821,6 +832,8 @@ then
 
 cat << EOF > "$CLONE_SQL"
 SET SESSION sql_log_bin=OFF;
+DROP USER IF EXISTS '$CLONE_USER'@'%';
+DROP USER IF EXISTS '$CLONE_USER'@'localhost';
 CREATE USER '$CLONE_USER'@'%' IDENTIFIED $WITH_OPTION BY '$CLONE_PSWD';
 GRANT all ON *.* TO '$CLONE_USER';
 CREATE USER '$CLONE_USER'@'localhost' IDENTIFIED $WITH_OPTION BY '$CLONE_PSWD';
@@ -831,9 +844,20 @@ EOF
     wsrep_log_debug "-> using: $CLONE_ENV $CLONE_BINARY_SAFE $DEFAULT_OPTIONS "
     wsrep_log_debug "-> Test connection as: -u$CLONE_USER -p$CLONE_PSWD -h $CLONE_HOST -P $CLONE_PORT"
     
+    #Define client
+    MYSQL_ACLIENT="$MYSQL_CLIENT -u$CLONE_USER -S$CLONE_SOCK --batch --skip_column_names --silent"
+    
+    
     #HERE IF WE WANT TO USE SAFE mysqld_safe
     eval WSREP_SST_CLONE=1 $CLONE_ENV $CLONE_BINARY $DEFAULT_OPTIONS \
-        --wsrep_provider=none --init_file="$CLONE_SQL" >> $CLONE_ERR 2>&1 &
+        --wsrep_provider=none --init_file="$CLONE_SQL" >> $CLONE_ERR &
+    
+    if [ "$?" == "0" ]; then
+        wsrep_log_error "-> User Creation on Joiner node failed, possible permission denied. Check permissions for "
+        #we will try to silently shutdown the instance
+        `$MYSQL_ACLIENT -e "SHUTDOWN" 2> /dev/null` || : 
+        exit 1
+    fi
 
     # wait for the receiver process to start
     until [ -n "$(cat $CLONE_PID_FILE 2>/dev/null)" ]
@@ -865,7 +889,7 @@ EOF
         sleep 1
     done
 
-    MYSQL_ACLIENT="$MYSQL_CLIENT -u$CLONE_USER -S$CLONE_SOCK --batch --skip_column_names --silent"
+#    MYSQL_ACLIENT="$MYSQL_CLIENT -u$CLONE_USER -S$CLONE_SOCK --batch --skip_column_names --silent"
     wsrep_log_info "-> MYSQL_ACLIENT: $MYSQL_ACLIENT"
     
     
